#server
server:
  port: 8888

#mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml

#logback
logging:
  config: classpath:logback-boot.xml

#spring datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_study
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdel: 3
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    spring.datasource.testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    redis:
      host: 127.0.0.1
      password: rental
      port: 6379
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
#jpa
jpa:
  show-sql: true
  properties:
  hibernate:
  hbm2ddl:
  auto: create